### PR TITLE
Fix buttons in /releases

### PR DESCRIPTION
**Pull request by philipnrmn**

### CODE REVIEW

**Comment by philipnrmn** [comment]
This PR competes with #839, looks like @cmaloney beat me to the punch

**Comment by cmaloney** [comment]
The real question is who has the page with the best internal spacing.

Mine: 
image

Yours:
image

**Comment by cmaloney** [comment]
Your width fix is quite a bit nicer, so I'd say go with it over mine

**Comment by philipnrmn** [comment]
Clockwise from top left: Opera, Chrome, Firefox, Safari

**Pull request merged**
