### PR TITLE
fixes for the sidebar

### PR DESCRIPTION
**Pull request by daveyheuser**
## What are your changes?
- purple arrow when it should just be grey
- margin of the file tree item

## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [ ] Medium

## I have completed these items:
- [ ] I have built locally and tested for broken links and formatting.
- [ ] If appropriate, I have added redirects.

### CODE REVIEW

**Comment by ashenden** [comment]
@mesosphere-ci retest this please

**Comment by ashenden** [comment]
@mesosphere-ci ok to test

**Comment by ashenden** [comment]
@mesosphere-ci retest this please

**Comment by ssk2** [comment]
ok to test

**Pull request merged**
