### PR TITLE
Add "In This Post" in docs sidebar

### PR DESCRIPTION
**Pull request by TimonVS**
## What are your changes?

Add part in the sidebar that allows you to navigate to sections in the docs.

There are still two issues left:
- [x] It overflows the footer in certain cases (when there's little content on the page) 
- [ ] It only works for `h1` tags right now, but a lot of docs pages are using `h2`. In other words, the docs are inconsistent. I could enable it for bot `h1` and `h2` tags if desirable.

CC: @ashenden 
## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [ ] Medium
## I have completed these items:
- [ ] I have built locally and tested for broken links and formatting.
- [ ] If appropriate, I have added redirects.

### CODE REVIEW

**Comment by TimonVS** [comment]
Note to self: remove `recalc` for sticky sidebar.

**Comment by ashenden** [comment]
Thanks @TimonVS looks great.  Following up on the remaining points:

- [ ] Update docs pages to downshift all h1s to h2s only in content body (same down the heading stack).
- [ ] Make the current h1 styling look like h2 styling (same down the heading stack). We may just simply strip the custom type styling.

**Comment by TimonVS** [comment]
@ashenden you guys are going to update the docs to use h1's, right?

**Comment by ashenden** [comment]
@TimonVS that will be up to @joel-hamill.  As long as the "in-this-post" feature relies on the `h1` tag (single `#` in markdown) from the source `.md` file, we are good.  How and when @joel-hamill decides to roll this out is on his team.  Thanks!

Also, seems their is a conflict above with this PR.

**Comment by TimonVS** [comment]
@ashenden Maybe we should split this between two separate issues? Or do you want to roll this out all at once?

**Comment by ashenden** [comment]
Retest this please.

**Comment by ashenden** [comment]
@TimonVS please resolve the conflicting file above, rebasing off `develop`.

**Comment by TimonVS** [comment]
@ashenden I fixed the conflicts.

**Comment by ashenden** [comment]
Nice work @TimonVS !! Merged.

**Comment by ashenden** [comment]
@joel-hamill the Docs site on dcos.io now has the same "in this post" style sidebar functionality that we have on the EE Docs site.  This nav only works for sections labeled with {{h1}} tags ({{#}} in markdown).  In general it would be smart to go back through our Markdown files and ensure we start our sections with {{h1}}s.

**Comment by joel-hamill** [comment]
this is great, thanks for delivering!

**Pull request merged**
