### PR TITLE
Add ability to add tags to docs

### PR DESCRIPTION
**Pull request by TimonVS**
## What are your changes?

Add ability to add tags to the docs (feature_maturity (`string`), enterprise (`boolean`))
## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [ ] Medium
## I have completed these items:
- [ ] I have built locally and tested for broken links and formatting.
- [ ] If appropriate, I have added redirects.
## If you included a comment with your commit, it appears here:

This is what it looks like:

### CODE REVIEW

**Comment by ashenden** [comment]
@TimonVS do you have a page I can test this on?  I did a search for `feature-maturity: experimental` and found it on `/dcos-docs/docs/1.8/usage/storage/external-storage.md`, but I don't see the tag when I view `/docs/1.8/usage/storage/external-storage/`.

**Comment by TimonVS** [comment]
@ashenden that's because it should be `feature_maturity` ;). I tested it by manually adding it to a markdown file.

**Comment by joel-hamill** [comment]
Should I be able to see this on a local doc build using [npm start](https://github.com/dcos/dcos-website#contribution-workflow)? I currently only see this topic properly tagged: https://github.com/dcos/dcos-docs/blob/c10fdc76b39d965994d7d0ba6b0d0b8f9c219e27/1.8/administration/installing/deploying-a-local-dcos-universe.md.

**Comment by joel-hamill** [comment]
And to clarify, we don't need the Enterprise tag on open source (non of this content is Enterprise, by design). The delineation between Enterprise and OSS is only an issue for Enterprise.

**Comment by TimonVS** [comment]
@joel-hamill Yes, you should be able to see it if you run with `npm start`. Should I remove the enterprise tag in its entirerty?

**Comment by ashenden** [comment]
@TimonVS yes.  Let's remove it entirely.

**Comment by joel-hamill** [comment]
@TimonVS okay, great, the preview is working https://cl.ly/1846160l012Y ! Can this badge be a hyperlink (e.g. https://cl.ly/1m3w0w1g2j2m)?

**Comment by TimonVS** [comment]
@joel-hamill should it always point to a header with the id `#preview`? And should it work for both preview and experimental?

**Comment by joel-hamill** [comment]
@TimonVS For preview it should look like https://docs.mesosphere.com/current/overview/feature-maturity/#preview. For experimental this: https://docs.mesosphere.com/1.8/usage/service-guides/hdfs/.

**Comment by TimonVS** [comment]
@joel-hamill @ashenden  Fixed.

**Comment by ashenden** [comment]
Retest this please.

**Comment by joel-hamill** [comment]
Changes look good to me.

**Pull request merged**
