### PR TITLE
Add linkchecker script

### PR DESCRIPTION
**Pull request by karlkfi**
Add linkchecker script
- Update Dockerfile to actually work
- Add ci/start.sh to start the server in docker
## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [X] Medium

### CODE REVIEW

**Comment by ssk2** [comment]
I have not tested this.

**Comment by karlkfi** [comment]
@ssk2 You know you want to:

```
SERVER_CID="$(ci/start.sh)"
ci/generate-linkchecker-report.sh
docker rm -f "${SERVER_CID}"
```

**Comment by ssk2** [comment]
In a bit.

**Comment by karlkfi** [comment]
Script Failures:

```
$ ci/validate-links.sh
WARNING 2016-10-31 17:41:32,631 MainThread Running as root user; dropping privileges by changing user to nobody.
LinkChecker 9.3              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2016-10-31 17:41:32+000
10 threads active,   102 links queued,   10 links in   5 URLs checked, runtime 1 seconds
10 threads active,    87 links queued,   25 links in  12 URLs checked, runtime 6 seconds
10 threads active,  1850 links queued,  615 links in  20 URLs checked, runtime 11 seconds
10 threads active,  1876 links queued,  669 links in  33 URLs checked, runtime 16 seconds
10 threads active,  1897 links queued,  768 links in  54 URLs checked, runtime 21 seconds
10 threads active,  1916 links queued,  870 links in  74 URLs checked, runtime 26 seconds
10 threads active,  1890 links queued,  896 links in  87 URLs checked, runtime 31 seconds
10 threads active,  1837 links queued,  949 links in  99 URLs checked, runtime 36 seconds
10 threads active,  2537 links queued, 1177 links in 111 URLs checked, runtime 41 seconds
10 threads active,  4434 links queued, 1736 links in 123 URLs checked, runtime 46 seconds
10 threads active,  4961 links queued, 1981 links in 139 URLs checked, runtime 51 seconds
10 threads active,  8497 links queued, 4415 links in 152 URLs checked, runtime 56 seconds
10 threads active, 10550 links queued, 9273 links in 167 URLs checked, runtime 1 minute, 1 seconds
10 threads active, 14083 links queued, 13164 links in 183 URLs checked, runtime 1 minute, 6 seconds
10 threads active, 16316 links queued, 16424 links in 195 URLs checked, runtime 1 minute, 11 seconds
10 threads active, 15049 links queued, 23965 links in 210 URLs checked, runtime 1 minute, 16 seconds
10 threads active, 16125 links queued, 28741 links in 224 URLs checked, runtime 1 minute, 21 seconds
10 threads active, 16697 links queued, 34920 links in 237 URLs checked, runtime 1 minute, 26 seconds
10 threads active, 17947 links queued, 41225 links in 253 URLs checked, runtime 1 minute, 31 seconds
10 threads active, 18477 links queued, 47232 links in 267 URLs checked, runtime 1 minute, 36 seconds
10 threads active, 18897 links queued, 53930 links in 277 URLs checked, runtime 1 minute, 41 seconds
10 threads active, 18664 links queued, 55294 links in 298 URLs checked, runtime 1 minute, 46 seconds
10 threads active, 18641 links queued, 55317 links in 319 URLs checked, runtime 1 minute, 51 seconds
10 threads active, 18627 links queued, 55331 links in 332 URLs checked, runtime 1 minute, 56 seconds
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
10 threads active, 18608 links queued, 55350 links in 348 URLs checked, runtime 2 minutes, 1 seconds
10 threads active, 18589 links queued, 55369 links in 362 URLs checked, runtime 2 minutes, 6 seconds
10 threads active, 18570 links queued, 55388 links in 381 URLs checked, runtime 2 minutes, 11 seconds
10 threads active, 18547 links queued, 55411 links in 400 URLs checked, runtime 2 minutes, 16 seconds
10 threads active, 18529 links queued, 55429 links in 415 URLs checked, runtime 2 minutes, 21 seconds
10 threads active, 18513 links queued, 55445 links in 429 URLs checked, runtime 2 minutes, 26 seconds
10 threads active, 18492 links queued, 55466 links in 445 URLs checked, runtime 2 minutes, 31 seconds
10 threads active, 18474 links queued, 55484 links in 461 URLs checked, runtime 2 minutes, 36 seconds
10 threads active, 18455 links queued, 55503 links in 476 URLs checked, runtime 2 minutes, 41 seconds
10 threads active, 18436 links queued, 55522 links in 491 URLs checked, runtime 2 minutes, 46 seconds
10 threads active, 18416 links queued, 55542 links in 512 URLs checked, runtime 2 minutes, 51 seconds
10 threads active, 18482 links queued, 55896 links in 530 URLs checked, runtime 2 minutes, 56 seconds
10 threads active, 18549 links queued, 56321 links in 546 URLs checked, runtime 3 minutes, 1 seconds
10 threads active, 18536 links queued, 56334 links in 555 URLs checked, runtime 3 minutes, 6 seconds
10 threads active, 18052 links queued, 56818 links in 564 URLs checked, runtime 3 minutes, 11 seconds
10 threads active, 18053 links queued, 56958 links in 586 URLs checked, runtime 3 minutes, 16 seconds
10 threads active, 17833 links queued, 57807 links in 601 URLs checked, runtime 3 minutes, 21 seconds
10 threads active, 17656 links queued, 57984 links in 619 URLs checked, runtime 3 minutes, 26 seconds

URL        `https://www.packet.net/preview/kb/where-do-i-locate-my-packet-project-id/'
Name       `Packet Project ID'
Parent URL http://172.17.0.1:3000/docs/latest/administration/installing/cloud/packet/, line 19, col 8
Real URL   https://www.packet.net/preview/kb/where-do-i-locate-my-packet-project-id/
Check time 1.604 seconds
Result     Error: 500 Internal Server Error
10 threads active, 16275 links queued, 61733 links in 643 URLs checked, runtime 3 minutes, 31 seconds
10 threads active, 13510 links queued, 65910 links in 687 URLs checked, runtime 3 minutes, 36 seconds
10 threads active, 12173 links queued, 67709 links in 743 URLs checked, runtime 3 minutes, 41 seconds

URL        `https://docs.mesosphere.com/community-edition-eula/'
Name       `https://docs.mesosphere.com/community-edition-eula/'
Parent URL http://172.17.0.1:3000/docs/1.8/administration/installing/cloud/aws/advanced/template-reference/, line 189, col 58
Real URL   https://docs.mesosphere.com/community-edition-eula/
Check time 3.154 seconds
Result     Error: 404 Not Found

URL        `https://www.packet.net/preview/kb/where-do-i-locate-my-packet-project-id/'
Name       `Packet Project ID'
Parent URL http://172.17.0.1:3000/docs/1.8/administration/installing/cloud/packet/, line 19, col 8
Real URL   https://www.packet.net/preview/kb/where-do-i-locate-my-packet-project-id/
Check time 1.604 seconds
Result     Error: 500 Internal Server Error
10 threads active, 11359 links queued, 68523 links in 765 URLs checked, runtime 3 minutes, 46 seconds
10 threads active,  9158 links queued, 70724 links in 791 URLs checked, runtime 3 minutes, 51 seconds
10 threads active,  7453 links queued, 72900 links in 818 URLs checked, runtime 3 minutes, 56 seconds
10 threads active,  6505 links queued, 73848 links in 847 URLs checked, runtime 4 minutes, 1 seconds

URL        `https://docs.docker.com/engine/userguide/networking/dockernetworks/'
Name       `DNI'
Parent URL http://172.17.0.1:3000/docs/1.8/administration/overlay-networks/, line 21, col 62
Real URL   https://docs.docker.com/engine/userguide/networking/dockernetworks/
Check time 1.874 seconds
Size       238.41KB
Result     Error: 404 Not Found
10 threads active,  4207 links queued, 76146 links in 880 URLs checked, runtime 4 minutes, 6 seconds
10 threads active,  2514 links queued, 78299 links in 920 URLs checked, runtime 4 minutes, 11 seconds

URL        `http://your-cluster.com/mesos'
Name       `http://your-cluster.com/mesos'
Parent URL http://172.17.0.1:3000/docs/1.8/usage/managing-services/uninstall/, line 77, col 49
Real URL   http://your-cluster.com/mesos
Check time 1.046 seconds
Result     Error: ConnectionError: HTTPConnectionPool(host='your-cluster.com', port=80): Max retries exceeded with url: /mesos (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb7d8b80d10>: Failed to establish ...

URL        `http://localhost/marathon'
Name       `http://localhost/marathon'
Parent URL http://172.17.0.1:3000/docs/1.8/usage/tutorials/autoscaling/microscaling-queue/, line 25, col 296
Real URL   http://localhost/marathon
Check time 1.037 seconds
Result     Error: ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /marathon (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb7d8b5d910>: Failed to establish a ne...
10 threads active,  1160 links queued, 79653 links in 956 URLs checked, runtime 4 minutes, 16 seconds

URL        `https://docs.mesosphere.com/manage-service/cassandra/'
Name       `install Cassandra'
Parent URL http://172.17.0.1:3000/docs/1.8/usage/tutorials/cassandra/, line 35, col 75
Real URL   https://docs.mesosphere.com/manage-service/cassandra/
Check time 2.036 seconds
Result     Error: 404 Not Found
10 threads active,   899 links queued, 79914 links in 998 URLs checked, runtime 4 minutes, 21 seconds

URL        `https://docs.mesosphere.com/manage-service/jenkins/'
Name       `Jenkins service documentation'
Parent URL http://172.17.0.1:3000/docs/1.8/usage/tutorials/jenkins/, line 214, col 5
Real URL   https://docs.mesosphere.com/manage-service/jenkins/
Check time 4.099 seconds
Result     Error: 404 Not Found
10 threads active,   626 links queued, 80187 links in 1025 URLs checked, runtime 4 minutes, 26 seconds
10 threads active,   353 links queued, 80460 links in 1067 URLs checked, runtime 4 minutes, 31 seconds
10 threads active,   274 links queued, 80539 links in 1100 URLs checked, runtime 4 minutes, 36 seconds
10 threads active,   148 links queued, 81123 links in 1177 URLs checked, runtime 4 minutes, 41 seconds
10 threads active,  1243 links queued, 82067 links in 1199 URLs checked, runtime 4 minutes, 46 seconds
10 threads active,  1206 links queued, 82104 links in 1206 URLs checked, runtime 4 minutes, 51 seconds
10 threads active,  3813 links queued, 84781 links in 1221 URLs checked, runtime 4 minutes, 56 seconds

URL        `https://docs.mesosphere.com/community-edition-eula/'
Name       `https://docs.mesosphere.com/community-edition-eula/'
Parent URL http://172.17.0.1:3000/docs/1.7/administration/installing/cloud/aws/advanced/template-reference/, line 141, col 58
Real URL   https://docs.mesosphere.com/community-edition-eula/
Check time 3.154 seconds
Result     Error: 404 Not Found
10 threads active,  5992 links queued, 87105 links in 1232 URLs checked, runtime 5 minutes, 1 seconds

URL        `https://www.packet.net/preview/kb/where-do-i-locate-my-packet-project-id/'
Name       `Packet Project ID'
Parent URL http://172.17.0.1:3000/docs/1.7/administration/installing/cloud/packet/, line 19, col 8
Real URL   https://www.packet.net/preview/kb/where-do-i-locate-my-packet-project-id/
Check time 1.604 seconds
Result     Error: 500 Internal Server Error
10 threads active,  8331 links queued, 90164 links in 1246 URLs checked, runtime 5 minutes, 6 seconds
10 threads active, 10539 links queued, 94380 links in 1261 URLs checked, runtime 5 minutes, 11 seconds
10 threads active, 12213 links queued, 98789 links in 1276 URLs checked, runtime 5 minutes, 16 seconds
10 threads active,  9638 links queued, 107071 links in 1291 URLs checked, runtime 5 minutes, 21 seconds

URL        `http://your-cluster.com/mesos'
Name       `http://your-cluster.com/mesos'
Parent URL http://172.17.0.1:3000/docs/1.7/usage/managing-services/uninstall/, line 76, col 49
Real URL   http://your-cluster.com/mesos
Check time 1.046 seconds
Result     Error: ConnectionError: HTTPConnectionPool(host='your-cluster.com', port=80): Max retries exceeded with url: /mesos (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb7d8b80d10>: Failed to establish ...

URL        `http://localhost/marathon'
Name       `http://localhost/marathon'
Parent URL http://172.17.0.1:3000/docs/1.7/usage/tutorials/autoscaling/microscaling-queue/, line 25, col 296
Real URL   http://localhost/marathon
Check time 1.037 seconds
Result     Error: ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /marathon (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb7d8b5d910>: Failed to establish a ne...
10 threads active,  6840 links queued, 115190 links in 1304 URLs checked, runtime 5 minutes, 26 seconds

URL        `https://docs.mesosphere.com/manage-service/jenkins/'
Name       `Jenkins service documentation'
Parent URL http://172.17.0.1:3000/docs/1.7/usage/tutorials/jenkins/, line 214, col 5
Real URL   https://docs.mesosphere.com/manage-service/jenkins/
Check time 4.099 seconds
Result     Error: 404 Not Found

URL        `https://docs.docker.com/engine/userguide/networking/dockernetworks/#the-default-bridge-network-in-detail'
Name       `Bridge Networking'
Parent URL http://172.17.0.1:3000/docs/1.7/usage/tutorials/tomcat/, line 51, col 70
Real URL   https://docs.docker.com/engine/userguide/networking/dockernetworks/
Check time 1.874 seconds
Size       238.41KB
Result     Error: 404 Not Found
10 threads active,  7137 links queued, 120519 links in 1317 URLs checked, runtime 5 minutes, 31 seconds

URL        `https://docs.mesosphere.com/manage-service/cassandra/'
Name       `install Cassandra'
Parent URL http://172.17.0.1:3000/docs/1.7/usage/tutorials/cassandra/, line 35, col 75
Real URL   https://docs.mesosphere.com/manage-service/cassandra/
Check time 2.036 seconds
Result     Error: 404 Not Found

URL        `https://docs.docker.com/engine/userguide/networking/dockernetworks/#the-default-bridge-network-in-detail'
Name       `Bridge Networking'
Parent URL http://172.17.0.1:3000/docs/1.7/usage/tutorials/tomcat/, line 51, col 70
Real URL   https://docs.docker.com/engine/userguide/networking/dockernetworks/
Check time 1.874 seconds
Size       238.41KB
Result     Error: 404 Not Found

URL        `https://docs.mesosphere.com/manage-service/cassandra/'
Name       `install Cassandra'
Parent URL http://172.17.0.1:3000/docs/1.7/usage/tutorials/cassandra/, line 35, col 75
Real URL   https://docs.mesosphere.com/manage-service/cassandra/
Check time 2.036 seconds
Result     Error: 404 Not Found
10 threads active,  6697 links queued, 126649 links in 1324 URLs checked, runtime 5 minutes, 36 seconds
10 threads active,  5590 links queued, 128161 links in 1342 URLs checked, runtime 5 minutes, 41 seconds
10 threads active,  4948 links queued, 129216 links in 1374 URLs checked, runtime 5 minutes, 46 seconds
10 threads active,  3970 links queued, 130194 links in 1405 URLs checked, runtime 5 minutes, 51 seconds
10 threads active,  3276 links queued, 131292 links in 1418 URLs checked, runtime 5 minutes, 56 seconds
10 threads active,  2368 links queued, 132200 links in 1431 URLs checked, runtime 6 minutes, 1 seconds
10 threads active,   711 links queued, 133923 links in 1455 URLs checked, runtime 6 minutes, 6 seconds
10 threads active,   410 links queued, 134224 links in 1477 URLs checked, runtime 6 minutes, 11 seconds

URL        `https://docs.mesosphere.com/manage-service/cassandra/'
Name       `install Cassandra'
Parent URL http://172.17.0.1:3000/docs/1.7/usage/tutorials/cassandra/, line 35, col 75
Real URL   https://docs.mesosphere.com/manage-service/cassandra/
Check time 2.036 seconds
Result     Error: 404 Not Found
10 threads active,   228 links queued, 135229 links in 1498 URLs checked, runtime 6 minutes, 16 seconds
10 threads active,   143 links queued, 135314 links in 1511 URLs checked, runtime 6 minutes, 21 seconds
10 threads active,    70 links queued, 135387 links in 1530 URLs checked, runtime 6 minutes, 26 seconds

Statistics:
Downloaded: 21.3MB.
Content types: 24689 image, 105745 text, 0 video, 0 audio, 5018 application, 10 mail and 5 other.
URL lengths: min=14, max=1050, avg=62.

That's it. 135467 links in 1541 URLs checked. 0 warnings found. 18 errors found.
Stopped checking at 2016-10-31 17:48:03+000 (6 minutes, 30 seconds)
```

**Comment by karlkfi** [comment]
Before merging, we should probably have all these links fixed.

**Comment by karlkfi** [comment]
Correction: This PR doesn't add the link validation to CI. I'll add another PR to do that so this one can be merged.

**Pull request merged**
