### PR TITLE
Ability to add events via JSON

### PR DESCRIPTION
**Pull request by TimonVS**
Add ability to add events via JSON (`./src/events.json`).
It'll automatically hide past events.

PR blocked by #734

### CODE REVIEW

**Comment by ashenden** [comment]
@TimonVS could you please rebase `develop` onto this branch?  I'm noticing some conflicts that I don't feel comfortable resolving myself.

**Comment by ashenden** [comment]
@TimonVS also, how is this branch different from this branch (https://github.com/dcos/dcos-website/tree/events)?

**Comment by TimonVS** [comment]
@ashenden that's an old branch which can be removed.

**Comment by ashenden** [comment]
Thanks.  Removed.

**Comment by ssk2** [comment]
@mesosphere-ci retest this please

**Pull request merged**
