### PR TITLE
Feature/fast data header

### PR DESCRIPTION
**Pull request by daveyheuser**
## What are your changes?
- Includes slider functionality and redesigned header
  - Slider also includes auto play
  - pauses on hover

## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [ ] Medium

## I have completed these items:
- [ ] I have built locally and tested for broken links and formatting.
- [ ] If appropriate, I have added redirects.

### CODE REVIEW

**Comment by ashenden** [comment]
Hey @daveyheuser assuming this isn't ready to merge yet, given @Martijn-Vermeulen is still working through the visuals right?

Also, could you make a point of rebasing from `develop`?  Looks like there are a few conflicts when I tried to do that myself.

**Comment by daveyheuser** [comment]
Hey @ashenden, this PR only includes the slider functionality and some the "features" row underneath the header. The second slide is commented out, so it won't show (slider code isn't triggered), therefore it's safe to merge this but I leave that up to you. I understand it if you want to wait till the illustration is done. If that's the case we could leave this PR as is for now.

> Also, could you make a point of rebasing from develop? Looks like there are a few conflicts when I tried to do that myself.
I'm gonna look into this and figure out how to fix this.

**Comment by ashenden** [comment]
Sounds good.  Let's hold until we are ready to go live with the new header.

As for the rebase.  You are simply rebasing your local `HEAD` (branch name) onto `develop`, resolving conflicts, and then force-pushing back to the branch at origin.  Effectively putting all your commits at the top of the commit history.

**Comment by daveyheuser** [comment]
I managed to merge `develop` and `feature/fast-data-header` with no errors.

**Comment by ashenden** [comment]
@daveyheuser I'm not sure you're doing the rebase correctly.  Check out this video of what I see when I attempt to rebase this branch onto `develop` (https://cl.ly/2f0m2y2G1x0T)

**Comment by daveyheuser** [comment]
Done, can you please retry this locally?

**Comment by ashenden** [comment]
@daveyheuser see this PR (https://github.com/dcos/dcos-website/pull/986#issuecomment-262195012) for a comment I left there.  Same comment applies here.

**Comment by daveyheuser** [comment]
This now includes the new illustration.

**Comment by ashenden** [comment]
@daveyheuser can we make sure these rotate automatically?  Right now they require manual interaction.

**Comment by ashenden** [comment]
According to @judithpatudith she'd like to launch with both Page Headers on the home page, but with Fast Data as the first one.

**Comment by daveyheuser** [comment]
Just fixed those things @ashenden, can you verify?

**Comment by ashenden** [comment]
@daveyheuser couple issues...
- [ ] Fast Data header should be the first header.
- [ ] Some crazy interaction on hover (https://cl.ly/0a471701173O).  Over time, the header starts rotating at an increasing rate until it looks like it's having a seizure.

**Comment by daveyheuser** [comment]
Fixed.

**Comment by ashenden** [comment]
Thanks.  Can we get rid of this outline (https://cl.ly/1n0g471r2136)?

Also, assuming the fast data page (`/fast-data`) is still in the other PR (https://github.com/dcos/dcos-website/pull/996).  This is fine.  I'm just going to hold off merging until both are ready to go.

**Comment by daveyheuser** [comment]
Oh, the good old Chrome outlines. I removed them, now off to changing the copy of the landing page so we're good to go!

**Pull request merged**
