### PR TITLE
add redirect for framework cleaning (DCOS_OSS-1622)

### PR DESCRIPTION
**Pull request by deric**
## Description

[Broken link to documentation when deleting service from DC/OS](https://jira.mesosphere.com/browse/DCOS_OSS-1622)

## Urgency
- [x] Medium

### CODE REVIEW

**Comment by pleia2** [comment]
ok to test

**Comment by pleia2** [comment]
retest this please

**Comment by judithpatudith** [comment]
👍

**Comment by judithpatudith** [comment]
retest this please

**Pull request merged**
