### PR TITLE
Feature/demos page

### PR DESCRIPTION
**Pull request by daveyheuser**
## Description
https://jira.mesosphere.com/browse/DCOS_SITE-159

## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-website#testing-your-updates-locally) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-website#contribution-workflow).

### CODE REVIEW

**Comment by judithpatudith** [comment]
Also, I just added a description to the tweeter demo, and all the other cards disappeared. Not sure what's up with that. Screencap attached: 
missing demos

**Comment by judithpatudith** [comment]
@daveyheuser We're getting there! Last couple nitpicks:
- [ ] Add a gray border around images/videos
- [ ] Add the demos page to the list of pages for the build to watch
- [ ] Change button text to "Try Demo"
- [ ] Change the "Packages" field to "Services"

**Comment by judithpatudith** [comment]
Hi @daveyheuser I added a video for the tweeter demo, and its not showing up correctly (see screencap): 
weird video

Also, please don't forget about the comments above! thanks!

**Comment by renesijnke** [comment]
Hi Judith,

I fixed the video issue and the 4 others issues. PR: https://github.com/dcos/dcos-website/pull/1270 (this will merge my changes to the feature/demos-page branch).

Regards,
Rene

**Comment by daveyheuser** [comment]
Sure is. I think we can just show them as a link next to the main call out button or as a secondary button. What would you want the label to be called?

**Comment by judithpatudith** [comment]
"Watch Video" please :)

**Comment by judithpatudith** [comment]
@daveyheuser I think this is almost ready. Still to do: 
- [ ] display pics instead of videos for non-featured demos
- [ ] add "Watch Video" links for non-featured demos
- [ ] change "Version" to "DC/OS Version"

**Comment by renesijnke** [comment]
Hi Judith,

I've completed the todo's, my changes can be found here: https://github.com/dcos/dcos-website/pull/1285

Regards,
Rene

**Comment by judithpatudith** [comment]
- [ ] All metadata fields should display well as arrays (currently the spacing is off)
- [ ] Align featured demo video with title rather than use case
- [ ] Make "Language" field plural ("Languages") 
- [ ] Build still seems like it's not auto-refreshing (this may be my problem)

**Comment by judithpatudith** [comment]
@renesijnke It looks like we're still missing 

- [ ] All metadata fields should display well as arrays (use case and languages are still not right)
- [ ] Use case should be a different font as it is in the mockup 
- [ ] My browser page now refreshes when I save changes to `demos.json` on a local build, but those changes still aren't reflected when the page refreshes. I still have to stop and start the build to make it work

Thanks for all your work on this!

**Comment by renesijnke** [comment]
Hi @judithpatudith 

By 'Use case' you mean text like 'Fast Data, Logging' right? Because this is already a bold font. http://jmp.sh/20OCO1X

What exactly do you mean by 'use case and language are still not right'? You mean the vertical alignment between the demos? http://jmp.sh/1V9OmgW So the buttons 'Try demo' should be vertical aligned with each other?

**Comment by judithpatudith** [comment]
@renesijnke 

Yes, the use case is "Fast Data, Logging" etc. For some reason, it's called `demo_name` in the demos.json file. I see that it is bolded, but in the mockup that we agreed upon, it was also a different font from the demo title, and I would like it to be a different font here as well.  

That same field should be able to take an array and display each element in the array correctly. All the elements are currently squished together, and there are no spaces between the elements. 

This is also a problem for the listed languages. They should be displayed correctly when demos.json contains an array there, and currently, it is missing spaces between the elements. 

The vertical alignment is also still inconsistent, but I'd rather just get the above changes in and ship this page than make other changes. We can file the vertical alignment problems as a bug later.

**Comment by renesijnke** [comment]
Hi @judithpatudith ,

I've fixed the issues & the font change. I've updated the feature/demos-page branch :)

Rene

**Comment by judithpatudith** [comment]
@renesijnke sorry to nitpick, but are you able to change the use case font? I think it was arial or something on the mockup, and I know its a silly little thing but I thought it made a big difference. For reference the mockup is [here](https://projects.invisionapp.com/share/Y2BFS3OJ9#/screens/232029957_Demos).

**Comment by renesijnke** [comment]
Hi @judithpatudith,

I've changed the font so it matches with the mockup.

Rene

**Pull request merged**
