### PR TITLE
Running DC/OS on SuSe Linux

### PR DESCRIPTION
**Pull request by zborisha**
## What are your changes?

Added new blog about running DCOS on Suse in Huawei

### CODE REVIEW

**Comment by ashenden** [comment]
@judithpatudith is this PR still relevant?  If not, can we close it out and delete the branch?

**Comment by judithpatudith** [comment]
@ashenden it is still relevant. I was having trouble figuring out how to build it locally and had asked @zborisha to, but he mentioned that he would be busy for a while. I'll try again and merge it later today.

**Comment by zborisha** [comment]
@judithpatudith I tested this locally just now and everything looks fine to me... formatting etc... anything else I can help with?

**Comment by ryadav88** [comment]
@mesosphere-ci test this please

**Comment by judithpatudith** [comment]
@mesosphere-ci test this please

**Comment by judithpatudith** [comment]
test this please

**Pull request merged**
