### PR TITLE
updating events carousel

### PR DESCRIPTION
**Pull request by judithpatudith**
## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [x] Medium

## I have completed these items:
- [x] I have built locally and tested for broken links and formatting.
- [ ] If appropriate, I have added redirects.

### CODE REVIEW

**Comment by judithpatudith** [comment]
@joel-hamill when you get a chance. Thank you!

**Comment by joel-hamill** [comment]
@judithpatudith looks like merge conflict

**Comment by judithpatudith** [comment]
Hey @joel-hamill, not sure what to do about these merge conflicts... I don't think anyone else edits the events carousel, and my manual build was fine. Any advice, or do you have time to show me how to resolve a merge conflict? Some of these events are coming up soon, so I'd like to get them up.

**Comment by joel-hamill** [comment]
@judithpatudith i use these instructions to resolve: https://confluence.atlassian.com/bitbucket/resolve-merge-conflicts-704414003.html. you could also try the embedded "command line instructions" link.

**Comment by judithpatudith** [comment]
@pyronicide What is the story with the validate-links test? A bunch of them failed but they're all related to dcos-docs, and not changes in this PR.

**Comment by joel-hamill** [comment]
@judithpatudith you can ignore the validate links test, but the merge conflict needs resolved.

**Pull request closed without merging**
