### PR TITLE
Feature/releases cta

### PR DESCRIPTION
**Pull request by daveyheuser**
## What are your changes?
Moved from 2 buttons and a direct download link to a more flexible solution.

## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [ ] Medium

## I have completed these items:
- [ ] I have built locally and tested for broken links and formatting.
- [ ] If appropriate, I have added redirects.

### CODE REVIEW

**Comment by ashenden** [comment]
@daveyheuser can you please rebase this branch onto `develop`? When I try to do this locally, I'm seeing conflicts.

**Comment by daveyheuser** [comment]
@ashenden Could you try merging it now? I tried it with Timon this morning and we didn't get any conflicts locally.

**Comment by ashenden** [comment]
@daveyheuser I think that somewhere along the way, the way you were merging and/or rebasing created some problems and duplicate commits.  Seems the same thing happened over here too (https://github.com/dcos/dcos-website/pull/987).

Check out this video (https://cl.ly/3n2o012f283N) showing the process by which I rebased your commits onto the `develop` branch and then used force-push to push the rebased timeline onto the `feature/releases-cta` branch.  That workflow is typically the correct one to follow...
1) Pull down the latest locally from your remote branch
2) Pull down `develop`, but use rebase instead of merge -- effectively rebasing the local `HEAD` branch (your working branch) onto `develop`.  This puts all your commits at the top, and makes for a very readable commit timeline.
3) Resolve conflicts if there are any
4) Push your changes back onto your branch at origin, but use force push.

I know it's annoying, but we strictly enforce the rebasing of commits here to make for a very clean/readable commit history.  If you follow that workflow above, you shouldn't have any issue, and should also be able to avoid the duplicate commits (not sure how that happens).

Doesn't appear to be any conflicts, and all tests are passing (other than the link checker).  But, given the duplicate commits above, I'm hesitant to merge into `develop` until you have a chance to review manually and make sure this is accurate.

**Comment by TimonVS** [comment]
@ashenden Seems like something went wrong with rebasing. But since the changelog looks fine and there are no conflicts, why not squash and merge the PR (click on the caret next to 'Merge pull request')? Then the history will not be hugely affected.

**Comment by daveyheuser** [comment]
I think I know how these occurred and it's because I rebased yesterday and didn't force push and therefore I had to rebase again. Both branches run locally without any conflicts though.

**Comment by ashenden** [comment]
Testing it out now.  Looks/functions great.  I'd like to request we change the behavior of the dropdown though.  Currently it functions like a `select` box.  It should function more like `button` that triggers a dropdown.

It is odd that when I click the dropdown, the first item is the prompt.  Also, it's strange that once I click an option, I now see that option printed out in the dropdown button text.  I was picture more like this (https://cl.ly/2n400a3H3140).

**Comment by ashenden** [comment]
@TimonVS unfortunately we have those options disabled for this repo (https://cl.ly/1E0f1U280l3s).  I'm less concerned about the duplicates as long as it works as expected and we just avoid it in the future.

**Comment by daveyheuser** [comment]
@ashenden I changed the way the interaction works. I think this comes very close to the bootstrap example you showed.

**Comment by daveyheuser** [comment]
I also have a version without the dropdown indicator, which in my opinion, looks a lot better.
screen shot 2016-11-23 at 15 33 35

**Comment by ashenden** [comment]
@daveyheuser could be a small bug, but this is what I see when I run it (https://cl.ly/2P442i0X013E0).  I do like the iteraction though.  And, unless it's also related to the same bug, clicking out of the dropdown, doesn't seem to dismiss it (https://cl.ly/2l3u2s03190A).

**Pull request merged**
