### PR TITLE
Refactor to Gulp

### PR DESCRIPTION
**Pull request by TimonVS**
I refactored some steps to Gulp to make builds much much faster (instead of having to rebuild everything on file save, it just rebuilds parts that need to be rebuild).

### CODE REVIEW

**Comment by TimonVS** [comment]
I still have to add uglification and minification for JS and CSS.

**Comment by karlkfi** [comment]
CI Error:

```
> NODE_ENV=development gulp serve

[13:10:41] Using gulpfile /dcos-website/gulpfile.js
[13:10:41] Starting 'build-site'...
[13:10:41] Starting 'build-docs-1.7'...
[13:10:41] Starting 'build-blog'...
[13:10:41] Starting 'copy-docs-images-1.7'...
[13:10:41] Starting 'copy'...
[13:10:41] Starting 'javascript'...
[13:10:42] Starting 'styles'...
[13:10:46] Finished 'javascript' after 4.61 s
[13:10:46] Finished 'build-blog' after 4.65 s
Transformers.markdown is deprecated, you must replace the :markdown jade filter, with :marked and install jstransformer-marked before you update to jade@2.0.0.

events.js:154
      throw er; // Unhandled 'error' event
      ^
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 4, column 1:
    
    ^
    at generateError (/dcos-website/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/dcos-website/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/dcos-website/node_modules/js-yaml/lib/js-yaml/loader.js:1040:9)
    at composeNode (/dcos-website/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/dcos-website/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/dcos-website/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at Object.load (/dcos-website/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at parse (/dcos-website/node_modules/front-matter/index.js:40:27)
    at extractor (/dcos-website/node_modules/front-matter/index.js:23:12)
    at /dcos-website/node_modules/gulp-front-matter/index.js:33:21
    at module.exports (/dcos-website/node_modules/tryit/tryit.js:8:9)
    at /dcos-website/node_modules/gulp-front-matter/index.js:32:9
    at vinylBufferStream (/dcos-website/node_modules/vinyl-bufferstream/index.js:50:5)
    at Transform.gulpFrontMatterTransform [as _transform] (/dcos-website/node_modules/gulp-front-matter/index.js:57:7)
    at Transform._read (/dcos-website/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Transform._write (/dcos-website/node_modules/readable-stream/lib/_stream_transform.js:147:83)

npm info lifecycle dcos-website@1.0.0~start: Failed to exec start script
npm ERR! Linux 4.1.7-coreos-r1
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! dcos-website@1.0.0 start: `NODE_ENV=development gulp serve`
npm ERR! Exit status 1
```

**Comment by TimonVS** [comment]
@karlkfi That means there's a markdown file with incorrect front matter (yaml). I'll investigate which file that is tomorrow.

**Comment by TimonVS** [comment]
@karlkfi found the culprit: https://github.com/dcos/dcos-docs/blob/master/1.7/administration/storage/mount-disk-resources.md. If you look at the raw source you'll see the front matter had too many dashes to separate it from the content. 
I created a PR for it: https://github.com/dcos/dcos-docs/pull/454.

**Comment by karlkfi** [comment]
needs rebase to fix tests

**Comment by TimonVS** [comment]
@karlkfi I rebased the code but the CI seems to be stuck.

**Pull request merged**
