### PR TITLE
Display member and child pages as descendant pages

### PR DESCRIPTION
**Pull request by jchn**
## Description

https://jira.mesosphere.com/browse/DCOS_SITE-154

## Urgency
- [x] Blocker 
- [ ] High
- [ ] Medium

Ping @joel-hamill @ashenden 

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-website#testing-your-updates-locally) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-website#contribution-workflow).

### CODE REVIEW

**Comment by joel-hamill** [comment]
This is still incorrect. The top-level pages should show links to all top-level pages and directories. This currently only shows the top-level directories (not individual pages): https://cl.ly/022q193P1W2Z 

cc: @ashenden

**Comment by jchn** [comment]
@joel-hamill are you sure you were checking the correct version? That page should look like this:
image

**Comment by joel-hamill** [comment]
@jchn still doesn't work for me. i'm seeing 
image

@ashenden can you try this out? maybe it's my local setup?

**Comment by joel-hamill** [comment]
ping @jchn @ashenden this is still broken. is there an update?

**Comment by joel-hamill** [comment]
@jchn is there an update here

**Comment by ashenden** [comment]
@jchn @daveyheuser I've hidden the `.related-pages` block until this issue can be resolved (https://github.com/dcos/dcos-website/pull/1187).

One possible concern is the fact that your calling this section `.related-pages`.  These is not related content, this is only descendants and their immediate children.

**Comment by jchn** [comment]
@ashenden @joel-hamill 

Seems like the issue was caused by a module which was recently updated.
We probably had different versions installed.

We bumped the version number in the package.json file, it should work after doing an `npm install`.

The `.hide` class has been removed from the ascending pages section so that section will be visible again.
 
The `.related-pages` class has been removed, it didn't have any css associated with it.

**Comment by joel-hamill** [comment]
@jchn I deleted `./build` and ran `npm start`, and I still do not see the child pages shown (https://github.com/dcos/dcos-website/pull/1168#issuecomment-287428168):
image

**Comment by daveyheuser** [comment]
Did you also run npm install before you ran npm start?

**Comment by joel-hamill** [comment]
@jchn i had not originally. just did the following, and still not showing:

```$ git branch -D fix/descendant-pages
Deleted branch fix/descendant-pages (was 9ee7ecd).
Joels-MacBook-Pro-10:dcos-website joelhamill$ git checkout fix/descendant-pages
Branch fix/descendant-pages set up to track remote branch fix/descendant-pages from origin.
Switched to a new branch 'fix/descendant-pages'
Joels-MacBook-Pro-10:dcos-website joelhamill$ npm install
npm WARN dcos-website@1.0.0 No license field.
Joels-MacBook-Pro-10:dcos-website joelhamill$ npm start```

**Comment by daveyheuser** [comment]
That's very strange. I was having the exact same issue as you have and npm-install solved it for me :( Can you have another look @jchn?

**Comment by daveyheuser** [comment]
Just checking, have you tried removing the node_modules folder before running npm install?

**Comment by ashenden** [comment]
This appears to be working fine for me locally.

**Comment by joel-hamill** [comment]
@jchn @daveyheuser deleting `npm_modules` did the trick. looks good. let's ship it!

**Comment by ashenden** [comment]
Just waiting on builds to pass and we'll merge

**Pull request merged**
