### PR TITLE
Redirect /brand to new brand guidelines

### PR DESCRIPTION
**Pull request by TimonVS**

### CODE REVIEW

**Comment by TimonVS** [comment]
Hmm, I'm also seeing a redirects file. Shouldn't that already do the job? CC: @jmanalus @ashenden

**Comment by jmanalus** [comment]
@TimonVS I updated the redirects file similar to how it was set up for the old media-kit link, but it's throwing a 404 when you go to  https://dev.dcos.io/brand/ (https://cl.ly/0N0O0C2Y1o1y)

The other redirects are working for https://dev.dcos.io/media-kit/ which directs to https://dev.dcos.io/brand/ and then gives a 404 error.

**Comment by jmanalus** [comment]
@ashenden Let's merge it, and see if the redirects work on dev

**Comment by ashenden** [comment]
@jmanalus please do a fresh rebase off `develop` onto this branch.

**Comment by TimonVS** [comment]
I'm sorry for not responding earlier @ashenden @jmanalus. Is it working properly now?

**Comment by jmanalus** [comment]
@TimonVS everything is working great. Thanks for fixing the issue for us.

**Pull request merged**
