### PR TITLE
Feature/community-page

### PR DESCRIPTION
**Pull request by daveyheuser**
## Description
https://jira.mesosphere.com/browse/DCOS_SITE-158

## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-website#testing-your-updates-locally) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-website#contribution-workflow).

### CODE REVIEW

**Comment by judithpatudith** [comment]
@daveyheuser The forward and back buttons on the events queue don't always seem to load for me (I think they disappeared after I switched a couple times between upcoming and recent). Can you look into it? Once that's fixed I think we're ready to go! Thanks!

**Comment by judithpatudith** [comment]
@daveyheuser also, when my browser window is very narrow the events queue doesn't seem to show up correctly. This wasn't a problem when I tested with the phone simulator on my computer, but it does happen in both chrome and safari (it works fine on Firefox).

**Comment by judithpatudith** [comment]
@daveyheuser it looks like the arrow now moves with whatever card it starts on. I'm attaching a screencap, hope it helps!
shifted arrow

**Comment by daveyheuser** [comment]
Tested locally and it appears to be working as expected so I think this is good to go.

**Comment by judithpatudith** [comment]
@daveyheuser I think this is ready, but I'm worried that I made a mistake... I tried to fix the merge conflict for the page, and now the docs page on my local build looks different than the ones on dev.dcos.io and dcos.io. I don't want to merge this before I know if things are ok or not. cc. @joel-hamill or @ashenden could you help me figure out what's up if you have a chance? Thanks!

**Comment by daveyheuser** [comment]
It works fine locally though and previews are rendering fine on dev.dcos.io too.

Did you try to remove your build and node_modules folders and run `npm install` & `npm start`?

screen shot 2017-04-26 at 09 25 01

**Pull request merged**
