### PR TITLE
Feature/tutorials page

### PR DESCRIPTION
**Pull request by renesijnke**
## Description
https://jira.mesosphere.com/browse/DCOS_SITE-160

## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-website#testing-your-updates-locally) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-website#contribution-workflow).

### CODE REVIEW

**Comment by judithpatudith** [comment]
Looks great! A few things:

- [ ] Can we change the URL to `/learning`
- [ ] Make the cards light grey so they pop a little
- [ ] It's not obvious to me that you need to click the version tag to get to the tutorial. Can we add a link to start the tutorial that points to the `/latest/` version?

**Comment by renesijnke** [comment]
Hi @judithpatudith ,

I've updated the learning page. I've made the title of the tutorial clickable. In my opinion better than adding a link.

Rene

**Comment by judithpatudith** [comment]
I still don't read that (visually) as very clickable. Could the whole card be clickable instead? Also, did you see @ashenden's recent comment on the invasion doc about the card dimensions/shape? See the sketch he left: https://cl.ly/26461I1n2X3d

**Comment by renesijnke** [comment]
Hi @judithpatudith ,

I've updated the layout of the page based on @ashenden suggestion. If you make the whole card clickable, you won't be able to click on version numbers in the bottom right.

**Comment by judithpatudith** [comment]
- [ ] The bigger cards don't seem to be determined by the `featured` field in the JSON anymore, and there will be only one featured card on the final page.
- [ ] This UX is inconsistent with the Demos page. Is it possible to include a  "start tutorial" button or similar?

**Comment by renesijnke** [comment]
Hi Judith,

The bigger cards are still determined by the feature field, tested this locally. I've added a start tutorial button. After @ashenden suggestion there are now 3 columns, this has a little side-effect that there is less space to work with to show the version tags.

**Comment by judithpatudith** [comment]
I'm seeing that now, thanks! could the tags sit on a second line or wrap? That might give them a bit more room.

**Comment by renesijnke** [comment]
Hi @judithpatudith ,

I've updated the page with the tags on a second row and the buttons aligned at the same height.

**Comment by judithpatudith** [comment]
@renesijnke do you have any thoughts on the buttons vs links question?

**Comment by judithpatudith** [comment]
Also, all the buttons just link to the top of the /learning page, not the tutorials themselves

**Comment by renesijnke** [comment]
@judithpatudith I pushed a fix for the buttons. I think a button is more appealing to user then a link :)

**Pull request merged**
