### PR TITLE
added accepteula removal to breaking changes

### PR DESCRIPTION
**Pull request by joel-hamill**
## What are your changes?

added accepteula removal to breaking changes of release notes.
## What is the urgency level of this change?
- [ ] Blocker
- [x] High
- [ ] Medium
## I have completed these items:
- [x] I have built locally and tested for broken links and formatting.
- [x] If appropriate, I have added redirects.

### CODE REVIEW

**Comment by lingmann** [comment]
👍

**Comment by joel-hamill** [comment]
@sascala ready for merge

**Comment by sascala** [comment]
lgtm

**Comment by joel-hamill** [comment]
recheck this please

**Comment by joel-hamill** [comment]
retest this please

**Pull request merged**
