### PR TITLE
Added H3C into DC/OS community

### PR DESCRIPTION
**Pull request by usultrared**
## Urgency
- [ ] Blocker 
- [v] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-website#testing-your-updates-locally) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-website#contribution-workflow).

### CODE REVIEW

**Comment by ashenden** [comment]
@usultrared your build is passing, which is the only thing that should block this PR. 
 However, there are number of broken links that are unrelated to your PR. 
 @joel-hamill @judithpatudith see the results of the test (https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-website-prs-validate-links/693/console) for reference to broken links we should probably resolve in another PR.

**Comment by usultrared** [comment]
@ashenden Looks like https://dcos.io/community/ is broken, too many historical Meetups. And H3C pic is not showing up.

**Comment by judithpatudith** [comment]
@usultrared I'm not seeing what is broken about it except for the new logo; can you be more specific?

**Comment by judithpatudith** [comment]
I noticed that there's an `@` symbol in one of the names of your logo files, could that be causing it not to display?

**Comment by judithpatudith** [comment]
Nope, I was looking through the file of logos, and it doesn't look like that's it. The other thing I noticed is that all the other logos have `.svg` files associated with them and I don't see one for the h3c logo. Other than that I'm out of ideas sorry :(

**Pull request merged**
