### PR TITLE
Improve docs sidebar styling

### PR DESCRIPTION
**Pull request by daveyheuser**
- [x] Text should indent consistently, and not wrap around the arrows or icons (https://cl.ly/2w3l0F3O2m19)
- [x] Space between items in the list could be reduced (https://cl.ly/1I3C3M2J1O0r).
- [x] The padding on nested list items could be reduced slightly to make more horizontal room available for the page titles.
- [ ] Vertical divider does not appear to go all the way to the bottom of the list (https://cl.ly/122P153p2A2D)

### CODE REVIEW

**Comment by TimonVS** [comment]
Vertical divider is fixed in `in-this-post` branch.

**Comment by ashenden** [comment]
@daveyheuser there is appears to be a conflicting file (see above).  Can you please rebase off `develop` and resolve?

**Comment by daveyheuser** [comment]
@ashenden I rebased the code.

**Comment by ashenden** [comment]
Retest this please

**Comment by ashenden** [comment]
@daveyheuser @TimonVS some comments from reviewing the changes after merging into `develop`:
[ ] The indent of the page icon vs. the arrow icon are different (https://cl.ly/0A3l2p0w3h3A)
[ ] When a menu item is unfolded, but not "active", the arrow is showing as purple (https://cl.ly/3m3x3i0F3s2Q).  Seems like this should only be purple when "active", right?
[ ] Vertical divider does not appear to go all the way to the bottom of the list (https://cl.ly/1S1r361A1m0f)

Could you please address these issues and reopen this PR or open a new one?  Thanks.

**Comment by daveyheuser** [comment]
Fixes are here: https://github.com/dcos/dcos-website/pull/968. @TimonVS is going to give the sidebar divider another look.

**Comment by ashenden** [comment]
Thanks!

**Pull request merged**
