### PR TITLE
Feature/author profiles blog

### PR DESCRIPTION
**Pull request by daveyheuser**
## What are your changes?
Show the author name as a link by adding `author_url` to the frontmatter of each markdown file for the blog.

## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [ ] Medium

## I have completed these items:
- [ ] I have built locally and tested for broken links and formatting.
- [ ] If appropriate, I have added redirects.

### CODE REVIEW

**Comment by daveyheuser** [comment]
You can checkout the previous commit in this branch but it's easier to quickly add `author_url` in the frontmatter of a post and see if it works.

**Comment by daveyheuser** [comment]
Oh damn editing a comment on Github isn't possible on mobile. But for example `author_url: http://google.com` would work.

**Comment by ashenden** [comment]
Looks good.  Can you make the link open in a new tab?

**Comment by daveyheuser** [comment]
Done!

**Pull request merged**
