### PR TITLE
Feature/docs descendants

### PR DESCRIPTION
**Pull request by daveyheuser**
## What are your changes?
Docs descendants. @jchn and I worked on showing descendants of docs posts.

## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [ ] Medium

## I have completed these items:
- [ ] I have built locally and tested for broken links and formatting.
- [ ] If appropriate, I have added redirects.

### CODE REVIEW

**Comment by judithpatudith** [comment]
@daveyheuser this isn't building well for me locally, did it work when you built it locally?

**Comment by ashenden** [comment]
Rebased onto `develop` and pushed back up to this branch.  I'm getting the following error...

```
➜  dcos-website git:(feature/docs-descendants) npm start

> dcos-website@1.0.0 start /Users/johnashenden/Development/dcos-website
> NODE_ENV=production gulp serve

[14:43:48] Using gulpfile ~/Development/dcos-website/gulpfile.js
[14:43:48] Starting 'build-site-templates'...
[14:43:48] Starting 'build-blog-templates'...
[14:43:48] Starting 'copy'...
[14:43:48] Starting 'browserify'...
[14:43:48] Finished 'browserify' after 47 ms
[14:43:48] Starting 'styles'...
[14:43:48] Starting 'nginx-config'...
[14:43:48] Starting 's3-config'...
[14:43:48] Starting 'build-docs-1.7'...
[14:43:48] Starting 'build-docs-1.8'...
[14:43:48] Starting 'build-docs-1.9'...
[14:43:48] Starting 'copy-docs-images-1.7'...
[14:43:48] Starting 'copy-docs-images-1.8'...
[14:43:48] Starting 'copy-docs-images-1.9'...
[14:43:48] Starting 'swagger-yaml'...
[14:43:48] Finished 'swagger-yaml' after 1.21 ms
[14:43:48] Finished 's3-config' after 219 ms
[14:43:48] Finished 'nginx-config' after 377 ms
Transformers.markdown is deprecated, you must replace the :markdown jade filter, with :marked and install jstransformer-marked before you update to jade@2.0.0.
[14:43:59] Finished 'styles' after 11 s
[14:43:59] Finished 'build-site-templates' after 11 s
[14:43:59] Finished 'build-blog-templates' after 12 s
events.js:141
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at Function (native)
    at Object.exports.compile (/Users/johnashenden/Development/dcos-website/node_modules/jade/lib/index.js:218:8)
    at handleTemplateCache (/Users/johnashenden/Development/dcos-website/node_modules/jade/lib/index.js:174:25)
    at Object.exports.compileFile (/Users/johnashenden/Development/dcos-website/node_modules/jade/lib/index.js:309:10)
    at /Users/johnashenden/Development/dcos-website/node_modules/consolidate/lib/consolidate.js:307:58
    at /Users/johnashenden/Development/dcos-website/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/Users/johnashenden/Development/dcos-website/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/johnashenden/Development/dcos-website/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/Users/johnashenden/Development/dcos-website/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/Users/johnashenden/Development/dcos-website/node_modules/consolidate/lib/consolidate.js:136:10)
    at exports.jade (/Users/johnashenden/Development/dcos-website/node_modules/consolidate/lib/consolidate.js:292:10)
    at convert (/Users/johnashenden/Development/dcos-website/node_modules/metalsmith-layouts/lib/index.js:134:7)
    at /Users/johnashenden/Development/dcos-website/node_modules/metalsmith-layouts/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/johnashenden/Development/dcos-website/node_modules/metalsmith-layouts/node_modules/async/lib/async.js:233:13)
    at async.forEach.async.each (/Users/johnashenden/Development/dcos-website/node_modules/metalsmith-layouts/node_modules/async/lib/async.js:209:22)
    at Ware.<anonymous> (/Users/johnashenden/Development/dcos-website/node_modules/metalsmith-layouts/lib/index.js:150:5)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! dcos-website@1.0.0 start: `NODE_ENV=production gulp serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dcos-website@1.0.0 start script 'NODE_ENV=production gulp serve'.
npm ERR! This is most likely a problem with the dcos-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production gulp serve
npm ERR! You can get their info via:
npm ERR!     npm owner ls dcos-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/johnashenden/Development/dcos-website/npm-debug.log
```

**Comment by daveyheuser** [comment]
Can you please retry? I rebased too and force pushed it to the branch. Don't forget to run `npm install` before running `npm start`.

**Comment by ashenden** [comment]
@daveyheuser I think there may be something else wrong here.  I have completely removed my `node_modules` folder, reinstalled all packages, and I'm still getting an error.

**Comment by daveyheuser** [comment]
Just rechecked it one more time locally and made sure everything is up to date and pushed again. Can you please pull and run it again? In the mean time I asked @jchn if he knows what's up. He built the descendants functionality so he knows everything about it (I only did the front-end).

**Comment by ashenden** [comment]
Just pulled down and still getting the same error.  You can also see this in the build test here - https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-website-prs/756/console

**Comment by daveyheuser** [comment]
We just pushed a fix. It worked on our end because we were building it with node 6 instead of 5, which is what you guys use. It turned out to be an easy fix so I hope it works for you guys now.

**Comment by ashenden** [comment]
I was able to build/run this time.  Thanks.

Some things I'm noticing:
[ ] The order the descendant pages are displaying should match the same sort order seen in the sidebar navigation (https://cl.ly/0m0T2z233r0F).
[ ] Let's consider truncating (...) the snippets so they aren't so long (4-5 lines should be enough).
[ ] For pages with child pages, we should the first 5 of their child pages in some kind of nested fashion.  Here is how we're doing this on the Enterprise Docs (https://cl.ly/1k2P1E063g34).
[ ] I'm thinking a thin horizontal line might be good to separate the content from the descendant TOC.  For example (https://cl.ly/430Y2L143a1l)

**Comment by judithpatudith** [comment]
This built for me locally and looks good. CI bot, Retest this please

**Comment by daveyheuser** [comment]
Hey Judith I'd like to make one minor change to this tomorrow before you merge it. Sorry!

**Comment by judithpatudith** [comment]
Sounds good. Ping me when you're ready?

**Comment by daveyheuser** [comment]
Will do.

**Comment by daveyheuser** [comment]
This should be good now.

**Comment by judithpatudith** [comment]
@daveyheuser with the new update, it doesn't look like snippets are truncating anymore, and I noticed that on the top level page, all the menu items for that page are incorrectly listed under 'support' (see screenshot) 
support_incorrect_links

**Comment by daveyheuser** [comment]
That's really strange. I'll look at it over the weekend if that's okay.

**Comment by judithpatudith** [comment]
Thanks!

**Comment by daveyheuser** [comment]
Alright, I made a very silly mistake the other day, but it's fixed now.

**Comment by judithpatudith** [comment]
@daveyheuser I'm seeing the same problems I was before. It seems like the summaries of single pages print out the titles of the multipage links that share their nested level. Hope that makes sense... Screen cap to corroborate.
last menu option under every page

**Comment by daveyheuser** [comment]
This should be fixed now.

**Comment by judithpatudith** [comment]
Awesome, thank you!

**Pull request merged**
