### PR TITLE
Feature/install page

### PR DESCRIPTION
**Pull request by daveyheuser**
## Description
https://jira.mesosphere.com/browse/DCOS_SITE-156

## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-website#testing-your-updates-locally) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-website#contribution-workflow).

### CODE REVIEW

**Comment by daveyheuser** [comment]
This PR also fixes https://jira.mesosphere.com/browse/DCOS_SITE-153

**Comment by judithpatudith** [comment]
@daveyheuser I just realized what was weird about the spacing: the sections were all alternating colors on the get-started page and shuffling them put two of the same color sections next to each other. Can you change the coloring so that the sections alternate colors, and put the spacing back? Thanks!

**Comment by renesijnke** [comment]
Hi Judith,

I changed the coloring and spacings of the sections back. See https://github.com/dcos/dcos-website/pull/1271

Regards,

Rene

**Comment by judithpatudith** [comment]
Ok, two nitpicks and we're done: 

- [ ] Can the cards for the install methods be very light gray to make them pop a bit from the white background? 
- [ ] Can we add links to the documentation above the install buttons for cloud (https://dcos.io/docs/latest/installing/cloud/) and On-prem (https://dcos.io/docs/latest/installing/custom/)?

**Comment by renesijnke** [comment]
Hi @judithpatudith ,

I've fixed the 3 issues stated above. The PR can be found here: https://github.com/dcos/dcos-website/pull/1279

Regards,
Rene

**Comment by judithpatudith** [comment]
@daveyheuser Could we comment out the Tutorials card and merge this now? That way we could uncomment it when the tutorials page goes up, and it won't be blocked in the meantime.

**Comment by renesijnke** [comment]
Hi Judith,

I've comment out the tutorials section and changed the documentation links. The PR can be found here: https://github.com/dcos/dcos-website/pull/1286

Regards,
Rene

**Comment by judithpatudith** [comment]
@renesijnke I meant the tutorials card in the resources section, not the whole DC/OS 101 tutorials section. Sorry for not being clear. Also, I'm not seeing where you gave the links a new line or centered them, I only see that the text has been changed.

**Comment by renesijnke** [comment]
Hi @judithpatudith,

I've re-enabled to 101 section and disabled the tutorial card. This is a screenshot of how the install cards now look like: http://jmp.sh/dk1zlvb.

**Comment by judithpatudith** [comment]
@renesijnke this is almost ready, but I can't figure out how to put the cards back to their normal height. I only wanted the Documentation links to be on a different line than the rest of the description, not to have a ton of extra space in the card. Thanks! Judith

**Pull request merged**
