### PR TITLE
PMC Meeting Blog 2016-12-09

### PR DESCRIPTION
**Pull request by judithpatudith**
## What is the urgency level of this change?
- [ ] Blocker
- [x] High
- [ ] Medium

## I have completed these items:
- [x] I have built locally and tested for broken links and formatting.
- [x] If appropriate, I have added redirects.

### CODE REVIEW

**Comment by judithpatudith** [comment]
Hey Ravi, please merge this when it goes green (I'm being optimistic that it will). Thanks!

**Comment by ryadav88** [comment]
@mesosphere-ci test this please

**Comment by judithpatudith** [comment]
@ryadav88 I rebased this, and now it builds, but fails the link check for a link in the developer's guide to the universe blog. I tried to fix that broken link with [PR 1033](https://github.com/dcos/dcos-website/pull/1033), but that link check failed with something different. Karl said I could probably just merge this with the failed check, but I'd love a second opinion...

**Comment by ryadav88** [comment]
yes, it can be merged with just website build check.

**Pull request merged**
