### PR TITLE
Feature/releases page

### PR DESCRIPTION
**Pull request by renesijnke**
## Description
https://jira.mesosphere.com/browse/DCOS_SITE-157

## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-website#testing-your-updates-locally) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-website#contribution-workflow).

### CODE REVIEW

**Comment by judithpatudith** [comment]
@renesijnke some things I'm noticing:

- [ ] The "get release" dropdown is still there instead of separate buttons 
- [ ] I'd love if the "release notes" link in the major release sections could pull from the highest number release URL in `releases.json` and if the text of the link could say 1.1.1 release notes (or whatever version number the release notes are for. 
- [ ] The "Older Versions" section should alternate colors depending on the section above it (as you can see, when I added 1.7 it blends into the 1.7 section)
- [ ] Does the version of the snapshot update every day? 
- [ ] We will have release notes for release candidates, so please add a release notes link to the RC card at the top?
- [ ] We won't always have an RC there (there isn't one now for example, so it would be nice if the version number said "coming soon" and the button disappeared when there is no candidate (maybe this is best done with commenting?)

**Comment by renesijnke** [comment]
Hi @judithpatudith ,

I'v made some changes.

- "The "get release" dropdown is still there instead of separate buttons" I think this will break the design
- "We won't always have an RC there..." This can be done by commenting yes :)
- "Does the version of the snapshot update every day?" I'm afraid this cannot be done automatically.

**Comment by judithpatudith** [comment]
@renesijnke 

- Yes, the snapshot updates every day.
- Can you propose any design alternatives to the dropdown? Perhaps it would be best to discuss these alternatives in JIRA? 

Thanks!

**Comment by renesijnke** [comment]
Hi judith,

I've updated the release page after your feedback on slack.

**Comment by judithpatudith** [comment]
- [ ] RC card should stay the same height when the release notes and links are commented out

**Comment by renesijnke** [comment]
Hi @judithpatudith ,

I've updated the layout.

**Comment by judithpatudith** [comment]
@renesijnke Thanks! This all looks good.

**Comment by judithpatudith** [comment]
Merged in a new request because too many conflicts were present in this one

**Pull request closed without merging**
