### PR TITLE
Footer updates

### PR DESCRIPTION
**Pull request by daveyheuser**
## Description
As discussed we're going to keep the footer the same but only add a Jira link to it. https://jira.mesosphere.com/browse/DCOS_SITE-176

## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-website#testing-your-updates-locally) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-website#contribution-workflow).

### CODE REVIEW

**Comment by judithpatudith** [comment]
@daveyheuser do you want me to merge this now, or wait for the other features of the footer that we discussed in the JIRA ticket here https://jira.mesosphere.com/browse/DCOS_SITE-176, and on our video call, specifically:
* Add "contact us" link that sends email to community-team@dcos.io
* Remove releases link once it is added to the top-level header
* Remove the large text and "get started" button
* Reduce the size of the Purple section of the footer

**Comment by judithpatudith** [comment]
Oh, is the purple section on the home page actually part of the home page and not the footer?

**Comment by daveyheuser** [comment]
I can add those things tomorrow but I think the footer can be merged without the navigation change. I think everything related to the navigation change should live in its own branch. 

And yes the purple footer is part of the homepage (and install if I'm right). The footer itself is just as small as it is on other pages.

**Comment by daveyheuser** [comment]
The contact us link appears to be working correctly and also doesn't break on mobile so this one should be good to go too.

**Pull request merged**
