### PR TITLE
Add checksum to releases page

### PR DESCRIPTION
**Pull request by jgarcia-mesosphere**
Hopefully this doesn't break formatting too badly.

### CODE REVIEW

**Comment by jgarcia-mesosphere** [comment]
@karlkfi can this be merged while we wait for the automagic process?

**Comment by karlkfi** [comment]
@jgarcia-mesosphere can you build this locally and screenshot the layout of the 3 release channel boxes?

**Comment by jgarcia-mesosphere** [comment]
Sadly... no. :(

```
$ npm start

> dcos-website@1.0.0 start /Users/jgarcia/source/dcos-website
> node index.js

/Users/jgarcia/source/dcos-website/index.js:3
const Metalsmith   = require('metalsmith')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! dcos-website@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dcos-website@1.0.0 start script 'node index.js'.
npm ERR! This is most likely a problem with the dcos-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls dcos-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jgarcia/source/dcos-website/npm-debug.log
```

**Comment by jgarcia-mesosphere** [comment]
Rebased against `develop` instead of `master`

**Comment by karlkfi** [comment]
does it build now? screenshot?

**Comment by jgarcia-mesosphere** [comment]
Nope, still won't build.

**Comment by karlkfi** [comment]
Works for me. Your node is out of date.

```
$ node --version
v5.10.0
```

That said, this isn't going to work:
release channels

**Comment by ashenden** [comment]
@karlkfi @jgarcia-mesosphere you guys still working on this or do you want to merge this in?

**Comment by jgarcia-mesosphere** [comment]
I don't have the cycles to follow up, and it's absolutely not presentable as-is. Unless someone else wants to take it up, I'd say let it go.

**Comment by karlkfi** [comment]
@ashenden a designer needs to figure out how to make it work, given that shas are giant.

**Comment by ashenden** [comment]
@jgarcia-mesosphere @karlkfi could someone help me understand what it is we are attempting to do here?  Do we need to print this out explicitly?  Examples of how other projects display this?

**Comment by karlkfi** [comment]
The desire is for users to be able to validate the integrity of their download. The simplest way to do this is with a file checksum. One option is to put the checksums in a sha256sum-style text file and share the link, another is to print them on the page next to the download links.

Having a checksum hosted in cleartext on the website doesn't guarantee that the file and checksum weren't both manipulated, but it does at least allow for validating that the download succeeded. If we want to also support authorship validation of the checksum, then we'd have to add gpg/pgp public/private key encryption. Most legit package managers already do authorship validation and integrity validation, so we'll want to support that in the future, but first we need checksums.

Here's one example of how to use a checksum: https://help.ubuntu.com/community/HowToSHA256SUM

- jwtproxy example with just checksums (on github): https://github.com/coreos/jwtproxy/releases
- Fedora example that uses encrypted and unencrypted checksums in the same file: https://getfedora.org/verify - https://getfedora.org/static/checksums/Fedora-Workstation-23-x86_64-CHECKSUM
- Eclipse downloads come with an unencrypted `.sha512` file next to the file: http://download.eclipse.org/eclipse/downloads/drops4/R-4.5.2-201602121500/  - http://download.eclipse.org/eclipse/downloads/drops4/R-4.5.2-201602121500/checksum/eclipse-SDK-4.5.2-win32.zip.sha512

**Comment by karlkfi** [comment]
I think I like the idea of having a (SHA256) link that goes to a plain-text `dcos_generate_config.sha256` file with an unencrypted checksum in sha256sum format. Ideally the build would generate the file, but for now it could be just included in dcos-website.

**Comment by karlkfi** [comment]
I think we're just gonna punt on this until it's automated by the build. Otherwise we're on the hook to manually update it.

https://dcosjira.atlassian.net/browse/DCOS-86

**Pull request closed without merging**
