### PR TITLE
Feature/packages page

### PR DESCRIPTION
**Pull request by renesijnke**
## Description
https://jira.mesosphere.com/browse/DCOS_SITE-180

## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-website#testing-your-updates-locally) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-website#contribution-workflow).

### CODE REVIEW

**Comment by judithpatudith** [comment]
Jenkins, Retest this please

**Comment by judithpatudith** [comment]
- [ ] Swap the text and new packages section
- [ ] When description text is too long it should truncate and link to the package browser URL for the package (now it just pushes everything else off the card).
- [ ] There should be room for at lease one sentence of description (perhaps make font smaller)
- [ ] Buttons should always be at the same height
- [ ] `status` tag should not be on the same line or wrap with the title
- [ ] Long titles take up almost the whole card

I pushed some of the text info to the branch so please pull it down if you're not sure what I'm trying to describe.

**Comment by renesijnke** [comment]
Hi Judith,

The issues are fixed. I've moved the status tag to the top right, otherwise it would conflict with the titles. In my opinion it looks much nicer now.

**Comment by judithpatudith** [comment]
Looks great! Last two tweaks: 

- [ ] Can the cta section at the bottom be white instead of gray so it doesn't blend into the new packages cards? 
- [ ] Could the card carousel start out filling the page instead of with the first card in the middle?

**Comment by renesijnke** [comment]
Hi Judith,

I've changed the background color of the cta background. Regarding the card carousel, I think this would be confusing for users :)

**Comment by judithpatudith** [comment]
@renesijnke what about it do you think would be confusing?

**Comment by judithpatudith** [comment]
@renesijnke never mind, after looking at it a bit I think I can see what you mean! Thanks!

**Pull request closed without merging**
