### PR TITLE
Feature/support for api docs

### PR DESCRIPTION
**Pull request by daveyheuser**
## What are your changes?
Implemented swagger-ui for api docs. These docs can be added to the website by including the following in the markdown files where they're needed. Each docs item should therefore have a .md and .yaml file, the code needed in order to load the yaml file is as follow:

```
<div class="swagger-section">
  <div id="message-bar" class="swagger-ui-wrap message-success" data-sw-translate=""></div>
  <div id="swagger-ui-container" class="swagger-ui-wrap" data-api="{path to yaml file}">

  <div class="info" id="api_info">
    <div class="info_title">Loading docs...</div>
  <div class="info_description markdown"></div>
</div>
```

This PR is related to: https://github.com/dcos/dcos-docs/pull/774

## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [ ] Medium

## I have completed these items:
- [ ] I have built locally and tested for broken links and formatting.
- [ ] If appropriate, I have added redirects.

### CODE REVIEW

**Comment by daveyheuser** [comment]
Sidenote: This branch is created from https://github.com/dcos/dcos-website/pull/1007, so I'll rebase this branch with develop once @jchn 's branch is merged.

**Comment by ashenden** [comment]
@daveyheuser I merged #1007 and rebased onto `develop` for you.  I switched to the dev branch you've been working on `dcos-docs` to preview the new API work.  Thanks!  Can you make it so that the widget doesn't spill outside of it's container though (https://cl.ly/1R1e1H2l0u3l)?

**Comment by joel-hamill** [comment]
@daveyheuser can you give me an example of `path to yaml file`. I have tried this, but it doesn't seem to work: 
```
<div class="swagger-section">
  <div id="message-bar" class="swagger-ui-wrap message-success" data-sw-translate=""></div>
  <div id="swagger-ui-container" class="swagger-ui-wrap" data-api="/1.8/api/iam.yaml">

  <div class="info" id="api_info">
    <div class="info_title">Loading docs...</div>
  <div class="info_description markdown"></div>
</div>
```

**Comment by daveyheuser** [comment]
@joel-hamill Just tested your code on my machine and figured that the path to your yaml file is missing the `/docs/` part. Here's an example .md file to get you going:

```---
post_title: Sample API docs
nav_title: Sample API docs
menu_order: 1
---

This could be an introductory text that describes the page you're looking at.

<div class="swagger-section">
  <div id="message-bar" class="swagger-ui-wrap message-success" data-sw-translate=""></div>
  <div id="swagger-ui-container" class="swagger-ui-wrap" data-api="/docs/1.8/api/certificate-authority.yaml">

  <div class="info" id="api_info">
    <div class="info_title">Loading docs...</div>
  <div class="info_description markdown"></div>
</div>
```

**Comment by joel-hamill** [comment]
@daveyheuser i still can't get it to work locally. i'll touch base with @ashenden

**Comment by ashenden** [comment]
@daveyheuser can you look into the width issue for the Swagger module?  I was able to get things setup on @joel-hamill's computer.

Also, appears to be a conflict (see above).  Can you rebase this onto `develop`?

**Comment by daveyheuser** [comment]
Will do!

**Comment by daveyheuser** [comment]
Done.

**Comment by joel-hamill** [comment]
@daveyheuser @ashenden looks good to me.

**Comment by ashenden** [comment]
@daveyheuser seems there is a file conflict.

**Comment by daveyheuser** [comment]
Looks like it conflicted with the main.js from another branch that got merged into develop earlier. I fixed it so it should rebase and / or merge fine now.

**Comment by joel-hamill** [comment]
Nice!

**Comment by karlkfi** [comment]
This PR broke the develop deploy, because it bumped the dcos-docs submodule to a commit sha that is not in dcos-docs master.

**Comment by ashenden** [comment]
@karlkfi yes, we should revert the commit sha to `dcos-docs` master.  But let's not revert the code contributed to the `dcos-website` repo from this PR.

**Comment by karlkfi** [comment]
@ashenden: Got it. Reverted.

**Pull request merged**
